name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clang:
   runs-on: ubuntu-latest
   container:
     image: "swift:5.2"
   steps:
     - name: clang
       run: clang --version
  build:

    runs-on: ubuntu-latest
    container:
      image: "swift:5.2"
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v

  test:
    runs-on: ubuntu-latest
    container:
      image: "swift:5.2"
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: swift test -v
